$(document).ready ->
  (($) ->
    $('#filter').keyup ->
      rex = new RegExp($(this).val(), 'i')
      $('.searchable tr').hide()
      $('.searchable tr').filter(->
        rex.test $(this).text()
      ).show()
      return
    return
  ) jQuery
  return

# ---
# generated by js2coffee 2.1.0
